# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets: # Contient la liste des filtres
        sizeOne: # Nom du filtre
            quality: 95 # Qualité de l'image
            filters: # Liste des filtres à appliquer
                upscale:
                    min: [ 530,350 ]
                thumbnail:
                    size: [ 530,350 ]
                    mode: outbound
        width300: # Nom du filtre
            quality: 95 # Qualité de l'image
            filters: # Liste des filtres à appliquer
                upscale:
                    min: [ 300,200 ]
                thumbnail:
                    size: [ 300,200 ]
                    mode: outbound

